# Generated by Django 4.1.7 on 2023-03-04 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="description",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
